package mc

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/ziggybadans/control-panel/internal/jobs"
)

// Dir exposes a server's directory for the file-management API.
func (m *Manager) Dir(id string) (string, error) {
	in, err := m.instErr(id)
	if err != nil {
		return "", err
	}
	return in.dir, nil
}

func (m *Manager) Versions(ctx context.Context, flavor string) ([]string, error) {
	return m.fetch.Versions(ctx, flavor)
}

// CreateServer provisions <root>/<id> and downloads the chosen server jar.
func (m *Manager) CreateServer(spec CreateSpec) (*jobs.View, error) {
	if err := spec.Validate(); err != nil {
		return nil, err
	}
	m.mu.Lock()
	if _, exists := m.instances[spec.ID]; exists {
		m.mu.Unlock()
		return nil, fmt.Errorf("server %q already exists", spec.ID)
	}
	for id, in := range m.instances {
		in.mu.Lock()
		port := in.port
		in.mu.Unlock()
		if port == spec.Port {
			m.mu.Unlock()
			return nil, fmt.Errorf("port %d is already used by %q", spec.Port, id)
		}
	}
	m.mu.Unlock()

	dir := filepath.Join(m.cfg.Root, spec.ID)
	if _, err := os.Stat(dir); err == nil {
		return nil, fmt.Errorf("directory %s already exists", dir)
	}

	return m.runner.Start("mc.create", spec.ID, func(ctx context.Context, out func(string)) error {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		jar, err := m.fetch.FetchJar(ctx, spec.Flavor, spec.Version, dir, out)
		if err != nil {
			// Leave nothing half-provisioned.
			_ = os.RemoveAll(dir)
			return err
		}
		if err := writeInitialFiles(dir, spec); err != nil {
			return err
		}
		out("writing initial configuration")

		m.mu.Lock()
		patch := m.overrides[spec.ID]
		if spec.Mem != "" {
			mem := spec.Mem
			patch.Mem = &mem
		}
		jarName := jar
		patch.Jar = &jarName
		m.overrides[spec.ID] = patch
		m.saveOverridesLocked()
		m.mu.Unlock()

		if err := m.Rescan(); err != nil {
			return err
		}
		out(fmt.Sprintf("server %q is ready — start it from the panel", spec.ID))
		return nil
	})
}

func writeInitialFiles(dir string, spec CreateSpec) error {
	props := fmt.Sprintf(
		"#Minecraft server properties\n#Generated by control-panel on %s\nserver-port=%d\nmotd=%s\nenable-rcon=false\nwhite-list=false\n",
		time.Now().Format(time.RFC3339), spec.Port, spec.MOTD)
	if err := os.WriteFile(filepath.Join(dir, "server.properties"), []byte(props), 0o644); err != nil {
		return err
	}
	if spec.AcceptEULA {
		eula := "# Accepted via control panel on " + time.Now().Format(time.RFC3339) + "\n" +
			"# https://aka.ms/MinecraftEULA\neula=true\n"
		if err := os.WriteFile(filepath.Join(dir, "eula.txt"), []byte(eula), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// UpdateJar downloads a new server jar into an existing server directory
// and points the launch configuration at it. The previous jar is kept on
// disk for manual rollback.
func (m *Manager) UpdateJar(id, flavor, version string) (*jobs.View, error) {
	in, err := m.instErr(id)
	if err != nil {
		return nil, err
	}
	if !ValidFlavors[flavor] {
		return nil, fmt.Errorf("invalid flavor %q", flavor)
	}
	if version == "" {
		return nil, fmt.Errorf("version is required")
	}
	return m.runner.Start("mc.jar", id, func(ctx context.Context, out func(string)) error {
		jar, err := m.fetch.FetchJar(ctx, flavor, version, in.dir, out)
		if err != nil {
			return err
		}
		m.mu.Lock()
		patch := m.overrides[id]
		jarName := jar
		patch.Jar = &jarName
		m.overrides[id] = patch
		m.saveOverridesLocked()
		newCfg := m.resolveCfgLocked(id, in.dir)
		m.mu.Unlock()

		in.mu.Lock()
		in.cfg = newCfg
		running := in.state == StateRunning || in.state == StateStarting
		in.mu.Unlock()

		go m.publish()
		if running {
			out(fmt.Sprintf("now using %s — restart the server to apply", jar))
		} else {
			out(fmt.Sprintf("now using %s", jar))
		}
		out("the previous jar was kept in the server directory for rollback")
		return nil
	})
}
